### ISSUE TITLE
合并相同ruleset导致基于selector的兼容产生问题

### ISSUE THREAD

**Issue by hax** [wangjeaf/CSSCheckStyle#2]
例子：

``` css
li:nth-child(even) {
  background:gray;
}
* html li.even {
  background:gray;
}
```

被压缩成了
`li:nth-child(even),* html li.even{background:gray}`
这导致兼容失效（因为一个selector不认，整个decl都被浏览器ignore了）
