### ISSUE TITLE
multiple box-shadow issues

### ISSUE THREAD

**Issue by allex** [wangjeaf/CSSCheckStyle#4]
t.css

``` css
.t{box-shadow:0 4px 5px 1px rgba(74, 116, 161, 0.1), inset 0 -1px #cadaea, inset 0 -2px #fbfcfe;}
```

fixstyle t.css

==> 
t.fixed.css

``` css
.t {
    box-shadow: 0 4px 5px 1px rgba(74, 116, 161, 0.1), inset 0 -1px #CADAEA inset 0 -2px #fbfcfe;
}
```

absolute, the result syntax is unexpected.
