### ISSUE TITLE
media query 忽略掉了

### ISSUE THREAD

**Issue by allex** [wangjeaf/CSSCheckStyle#6]
a.css

``` css
.x{padding:2px;}
@media screen and (max-device-width:768px) and (orientation:portrait){
    .x{padding:3px;}
}
```

[allex@ALLEX:~/dev/test]$ csscompress -p a.css 
.x{padding:2px}
